#!/bin/sh
mkdir -p target
gcc -c meow.s -o target/amogus.o || exit
gnu() { shift 1 && gcc "$@"; }
"$(command -v ~/stuff/zig/zig || echo gnu)" \
cc -static -nostdlib -nodefaultlibs target/amogus.o -o target/amogus || exit
objdump -d target/amogus
strip --strip-section-headers -K entry target/amogus
du -b target/amogus

